# https://github.com/k-paxian/dart-package-publisher
name: 'Dart and Flutter Package Publisher'
description: 'Continuously Test & Publish Dart and Flutter Package To Pub.dev When Version Changed'
author: 'k-paxian'
branding:
  color: 'blue'
  icon: 'package'
inputs: 
  accessToken:
    description: '(Required) Token from ~/.pub-cache/credentials.json. Use secrets.OAUTH_ACCESS_TOKEN'
    required: true
  refreshToken:
    description: '(Required) Token from ~/.pub-cache/credentials.json. Use secrets.OAUTH_REFRESH_TOKEN'
    required: true
  credentialJson:
    description: '(Optional) Overrides accessToken and refreshToken. Whole content of ~/.pub-cache/credentials.json. Use secrets.CREDENTIAL_JSON'
    required: false
  relativePath:
    description: '(Optional) Path to your package root in your repository'
    required: false
    default: ''
  dryRunOnly:
    description: '(Optional) Perform dry run only, no real publishing'
    required: false
    default: false
  testRunOnly:
    description: '(Optional) Perform unit tests run only, no real publishing'
    required: false
    default: false
  skipTests:
    description: '(Optional) Skip unit tests run'
    required: false
    default: false
  suppressBuildRunner:
    description: '(Optional) Suppress using `build_runner` for unit tests run'
    required: false
    default: false
  format:
    description: '(Optional) Format code of project to get better score in pub.dev'
    required: false
    default: false
  force:
    description: '(Optional) Force publishing even if pub tool throws warnings, hints, etc'
    required: false
    default: false
  flutter:
    description: '(Optional) Flutter package type'
    required: false
    default: false
  flutterBranch:
    description: '(Optional) Flutter branch to use, stable, master, main, dev, etc.'
    required: false
    default: 'stable'
outputs:
  success:
    description: 'Result, "true" if actual publishing happened, "false" otherwise'
  package:
    description: 'Package name from pubspec'
  localVersion:
    description: 'Package local version from pubspec'
  remoteVersion:
    description: 'Package remote version from pub.dev'
  dartVersion:
    description: 'Dart SDK version which is being used to run tests & publish'
  flutterVersion:
    description: 'Flutter SDK version which is being used to run tests & publish'
runs:
  using: 'docker'
  image: 'Dockerfile'