include: package:flutter_lints/flutter.yaml

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
analyzer:
  exclude:
    # Ignore generated files
    - "**/*.g.dart"
    - lib/src/impl/native_iris_api_engine_bindings.dart
    - test_apps/**
    
linter:
  rules:
    # - public_member_api_docs