include: package:flutter_lints/flutter.yaml
analyzer:
  exclude:
    # Ignore generated files
    - "**/*.g.dart"
    - lib/src/generated/*.dart
    - integration_test_app/**
    - test/**
    
linter:
  rules:
    public_member_api_docs: false
