targets:
  $default:
    sources:
      exclude:
        - example/
        - example/**/**.dart
    builders:
      source_gen|combining_builder:
        options:
          ignore_for_file:
          - non_constant_identifier_names
          - deprecated_member_use_from_same_package
          - unused_element