name: 'NativeIrisApiEngineBinding'
description: 'Bindings to IrisApiEngine'

output: 'lib/src/impl/native_iris_api_engine_bindings.dart'

headers:
  entry-points:
    - 'third_party/include/iris_c_api.h'
  include-directives:
    - 'third_party/include/iris_c_api.h'
    - 'third_party/include/iris_base.h'
    - 'third_party/include/iris_video_processor_c.h'

preamble: |
  // ignore_for_file: camel_case_types, non_constant_identifier_names

llvm-path:
  - '/usr/local/opt/llvm'