/// Generated by terra, DO NOT MODIFY BY HAND.

#ifndef FAKE_IMEDIARECORDER_INTERNAL_H_
#define FAKE_IMEDIARECORDER_INTERNAL_H_

#include "IAgoraMediaRecorder.h"

namespace agora {
namespace rtc {
class FakeIMediaRecorderInternal : public agora::rtc::IMediaRecorder {
  virtual int
  setMediaRecorderObserver(agora::rtc::RtcConnection const &connection,
                           media::IMediaRecorderObserver *callback) override {
    return 0;
  }

  virtual int
  startRecording(agora::rtc::RtcConnection const &connection,
                 media::MediaRecorderConfiguration const &config) override {
    return 0;
  }

  virtual int
  stopRecording(agora::rtc::RtcConnection const &connection) override {
    return 0;
  }

  virtual void release() override {}
};

} // namespace rtc
} // namespace agora

#endif // FAKE_IMEDIARECORDER_INTERNAL_H_
