include: shared:rtc_4.0.0.229/shared_configs.yaml

language: dart

legacy_renders:
  - DartSyntaxRender
  - DartEventHandlerParamJsonRender
  - DartCallApiRender
  - LegacyDartEventHandlerRender
  - DartStructToJsonSerializableRender
  - DartCallApiEventHandlerBufferExtRender
  - DartForwardExportRender