include: shared:rtc_4.0.1.5/shared_configs.yaml

language: dart

legacy_renders:
  - DartSyntaxRender
  - DartEventHandlerParamJsonRender
  - DartCallApiRender
  - LegacyDartEventHandlerRender
  - DartStructToJsonSerializableRender
  - DartCallApiEventHandlerBufferExtRender
  - DartForwardExportRender