package io.agora.agora_rtc_engine_example

import android.os.Bundle
import io.agora.agora_rtc_engine_example.custom_audio_source.CustomAudioPlugin
import io.agora.agora_rtc_engine_example.custom_audio_source.CustomAudioSource
import io.agora.rtc.base.RtcEnginePlugin
import io.flutter.embedding.android.FlutterActivity
import io.flutter.embedding.engine.FlutterEngine
import java.lang.ref.WeakReference

class MainActivity: FlutterActivity() {

  private val customAudioPlugin = CustomAudioPlugin(WeakReference(this))

  override fun onCreate(savedInstanceState: Bundle?) {
    super.onCreate(savedInstanceState)

    // Register the `CustomAudioPlugin` to interect with the `RtcEngine`
    RtcEnginePlugin.register(customAudioPlugin)
  }

  override fun configureFlutterEngine(flutterEngine: FlutterEngine) {
    super.configureFlutterEngine(flutterEngine)
    // The `CustomAudioSource` is generated by [pigeon](https://pub.dev/packages/pigeon), you can see the
    // the definiton on `example/lib/examples/advanced/custom_audio/custom_audio_source_api.dart`
    CustomAudioSource.CustomAudioSourceApi.setup(flutterEngine.dartExecutor, customAudioPlugin)
  }

  override fun onDestroy() {
    super.onDestroy()

    RtcEnginePlugin.unregister(customAudioPlugin)
  }
}
