import UIKit
import Flutter

@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate {
    
    private var customAudioSourcePlugin: CustomAudioPlugin!
    
    override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
    ) -> Bool {
        let controller : FlutterViewController = window?.rootViewController as! FlutterViewController

        customAudioSourcePlugin = CustomAudioPlugin()
        
        // The `CustomAudioSourceApiSetup` is generated by [pigeon](https://pub.dev/packages/pigeon), you can see the
        // the definiton on `example/lib/examples/advanced/custom_audio/custom_audio_source_api.dart`
        CustomAudioSourceApiSetup(
        controller.binaryMessenger, customAudioSourcePlugin)

        // Register the `CustomAudioPlugin` to interect with the `AgoraRtcEngineKit`
        RtcEnginePluginRegistrant.register(customAudioSourcePlugin)
          
        GeneratedPluginRegistrant.register(with: self)
          
        return super.application(application, didFinishLaunchingWithOptions: launchOptions)
    }
    
    override func applicationWillTerminate(_ application: UIApplication) {
        RtcEnginePluginRegistrant.unregister(customAudioSourcePlugin)
    }
}
