// Autogenerated from Pigeon (v1.0.7), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import <Foundation/Foundation.h>
@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN


/// The codec used by CustomAudioSourceApi.
NSObject<FlutterMessageCodec> *CustomAudioSourceApiGetCodec(void);

@protocol CustomAudioSourceApi
- (void)setExternalAudioSourceEnabled:(NSNumber *)enabled sampleRate:(NSNumber *)sampleRate channels:(NSNumber *)channels error:(FlutterError *_Nullable *_Nonnull)error;
- (void)setExternalAudioSourceVolumeSourcePos:(NSNumber *)sourcePos volume:(NSNumber *)volume error:(FlutterError *_Nullable *_Nonnull)error;
- (void)startAudioRecordSampleRate:(NSNumber *)sampleRate channels:(NSNumber *)channels error:(FlutterError *_Nullable *_Nonnull)error;
- (void)stopAudioRecordWithError:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void CustomAudioSourceApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<CustomAudioSourceApi> *_Nullable api);

NS_ASSUME_NONNULL_END
