
      /// GENERATED BY terra, DO NOT MODIFY BY HAND.
      
      // ignore_for_file: public_member_api_docs, unused_local_variable, unused_import, annotate_overrides
      
      import '/src/binding_forward_export.dart';
      import '/src/binding/impl_forward_export.dart';
      import 'package:iris_method_channel/iris_method_channel.dart';
      
      class Impl  implements  {
          Impl(this.irisMethodChannel);

          @protected
              final IrisMethodChannel irisMethodChannel;
          
          
          @protected
          Map<String, dynamic> createParams(Map<String, dynamic> param) {
            return param;
          }

          
          @protected
          bool get isOverrideClassName => false;

          
          @protected
          String get className => '';

          
        }
      