name: Code gen

on:
  workflow_dispatch:
    inputs:
      target_branch:
        description: The branch to run code-gen
        type: string
        required: true
        default: 'main'

      version:
        description: 'The version of native sdk in terra-script'
        required: false
        type: string
        default: ''

jobs:
  run_code_gen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.target_branch }}
          fetch-depth: 0
      - name: enable corepack
        run: corepack enable
      - name: set node
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      - name: Reconfigure git to use HTTP authentication
        run: |
          git config --global url."https://${{ secrets.GH_TOKEN }}@github.com/".insteadOf ssh://git@github.com/
      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "15.0.6" # Need ping version to 15.x
          directory: ${{ runner.temp }}/llvm
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Run code-gen
        run: |
          bash scripts/code_gen.sh ${{ inputs.version }}

      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y%m%d')" >> "$GITHUB_OUTPUT"

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Auto generate codes for native sdk version ${{ inputs.version }}"
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: auto-code-gen-${{ steps.date.outputs.date }}
          base: ${{ inputs.target_branch }}
          delete-branch: true
          title: "Auto generate codes for native sdk ${{ inputs.version }}"
          body: |
            Auto generate codes for native sdk version ${{ inputs.version }}

            *This pull request is opened by bot*
          labels: |
            ci:skip
          reviewers: |
            littleGnAl
