name: Tag the special version 🚀

on:
  pull_request:
    types:
      - closed

jobs:
  release_special_if_merged:
    if: ${{ github.event.pull_request.merged == true && 
            contains(github.event.pull_request.labels.*.name, 'ci:ready_release_special') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.base.ref }}
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install release-it
        run: |
          npm install -g release-it
          npm install -g release-it/bumper
          npm install -g release-it/conventional-changelog
      - name: git config
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
      - run: |
          PUBSPEC_VERSION=$(grep 'version: ' pubspec.yaml | sed -e 's,.*: \(.*\),\1,')
          echo "pubspec version: ${PUBSPEC_VERSION}"

          release-it ${PUBSPEC_VERSION} \
            --no-git.commit \
            --'git.commitMessage="chore: release ${version}"' \
            --git.tag \
            --'git.tagName="${version}"' \
            --'git.tagAnnotation="Release ${version}"' \
            --git.push \
            --no-github.release \
            --no-github.web \
            --ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}