name: Schedule run ci internal

on:
  pull_request:

jobs:
  check_permission:
    name: Check permission
    runs-on: ubuntu-latest
    timeout-minutes: 60
    outputs:
        is_schedule_run_ci: ${{ steps.check-label-step.outputs.result }}
    steps:
      - name: Check for Secret availability
        id: check-label-step
        # perform secret check & put boolean result as an output
        shell: bash
        run: |
          if [ "${{ secrets.MY_APP_ID }}" != '' ]; then
            echo "is_schedule_run_ci=0" >> $GITHUB_OUTPUT;
          else
            echo "is_schedule_run_ci=1" >> $GITHUB_OUTPUT;
          fi

  schedule_ci:
    name: Schedule run ci
    needs: check_permission
    # If the PR requested by a external contributor, the secrets.MY_APP_ID should be empty, and skip this workflow
    if: ${{ needs.check_permission.outputs.is_schedule_run_ci == 0 }}
    uses: ./.github/workflows/build.yml
    secrets:
      MY_APP_ID: ${{ secrets.MY_APP_ID }}
            