# Cron syntax
# ┌───────────── minute (0 - 59)
# │ ┌───────────── hour (0 - 23)
# │ │ ┌───────────── day of the month (1 - 31)
# │ │ │ ┌───────────── month (1 - 12 or JAN-DEC)
# │ │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
# │ │ │ │ │
# │ │ │ │ │
# │ │ │ │ │
# * * * * *

name: 'schedule: stale issues'

on:
  workflow_dispatch:
    
  schedule:
    - cron: '30 8 * * *' # This workflow will run every day at 8:30 AM

permissions:
  issues: write

jobs:
  schedule_stals_issues:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/stale@v9
       with:
         repo-token: ${{ github.token }}
         # Idle number of days before marking issues/PRs stale
         # If set to a negative number like -1, no issues or pull requests will be marked as stale automatically.
         days-before-stale: -1
         # Idle number of days before closing stale issues/PRs
         # If set to a negative number like -1, the issues or the pull requests will never be closed automatically.
         days-before-close: -1
         # Override days-before-stale for issues only
         days-before-issue-stale: 14
         # Override days-before-close for issues only
         days-before-issue-close: 5
         # Comment on the staled issues
         stale-issue-message: 'This issue is stale because it has been open 14 days with no activity. Remove stale label or comment or this will be closed in 5 days.'
         # Comment on the staled issues while closed
         close-issue-message: 'This PR was closed because it has been stalled for 5 days with no activity.'
         # If set to true, the issues or the pull requests with an assignee will not be marked as stale automatically.
         exempt-all-assignees: true
         